### PR TITLE
Clean pull-request for Beluga scripts from Alex C.

### PR DESCRIPTION
**Pull request by jbrillon**
Supersedes PR#75 created by Alex to clean up commits that got added from another draft PR.

### CODE REVIEW

**Comment by dougshidong** [comment]
Thanks for the clean PR. @AlexanderCicchino any reason why it's a new file rather than modifying `job_compile_PHiLiP.sh`? Becomes confusing if we have multiple files that supposedly do the same, but one becomes deprecated.

**Comment by AlexanderCicchino** [comment]
Yes, for the simple reason that I didn't know about the file job_compile_PHiLiP.sh. 
In hindsight, it is nice for new students to see how the changes were made as Beluga updated their modules.

**Comment by jbrillon** [comment]
@dougshidong @AlexanderCicchino Should I overwrite `job_compile_PHiLiP.sh` so this can be merged?

**Comment by dougshidong** [comment]
Yes please.

**Comment by jbrillon** [comment]
Done

**Comment by dougshidong** [comment]
> Yes, for the simple reason that I didn't know about the file job_compile_PHiLiP.sh.
> In hindsight, it is nice for new students to see how the changes were made as Beluga updated their modules.

Makes sense. I sent you the script before it was commited.

Thanks for the change Julien.

**Pull request merged**
