### PR TITLE
Small bugfix from PR #263

### PR DESCRIPTION
**Pull request by cpethrick**
Compiling the most recent version of master on my computer gave the following error, introduced in PR #263:
image

I removed the semicolons and can confirm that the code builds in both release and debug mode.

### CODE REVIEW

**Comment by cpethrick** [comment]
Here are the `ctest` results from this run. Note that the test `NNLS_dependent_columns` failed. From conversation with @tofstie, it seems like the issue is related to the random seed used to generate some arrays. I've opened issue #266, hopefully it is a fairly easy fix!

[log.txt](https://github.com/user-attachments/files/16751414/log.txt)

**Review by PranshulThakur — APPROVED** [review]
LGTM!

**Review by ssaishruthi98 — APPROVED** [review]
LGTM! 😄

**Review by jbrillon — COMMENTED** [review]
LGTM

**Pull request merged**
