### PR TITLE
Replace `use_collocated_nodes` by `flux_nodes_type`

### PR DESCRIPTION
**Pull request by jbrillon**
PR to replace the `use_collocated_nodes` parameter by `flux_nodes_type`; allowing for over-integration with either GLL or GL flux nodes. For collocation, set `flux_nodes_type = GLL` and `overintegration=0` in the `.prm` file.

### CODE REVIEW

**Review by cpethrick — APPROVED** [review]
LGTM. Glad this bug was found!

**Comment by dougshidong** [comment]
Definition of collocation means that solution nodes are the same as integration nodes... If you overintegrate, it's not collocation anymore.

**Comment by AlexanderCicchino** [comment]
@dougshidong agreed. We'll change the parameter name to distinguish between GL and GLL integration.

**Comment by jbrillon** [comment]
Attempting to add @cyanmcg as a reviewer

**Review by PranshulThakur — APPROVED** [review]
LGTM! Thanks for the changes. Since GLL hasn't been used with overintegation in a long time, there might be some regions in the code hardcoded to overintegration = 0 (something to watch out for in future).

**Pull request merged**
