### PR TITLE
Templated Operators with typename real.

### PR DESCRIPTION
**Pull request by AlexanderCicchino**
Templated operators class with type real for input, output, and weight vectors. The basis is assumed to stay as double for the sum-factorization. This allows operators to be used with AD type.

### CODE REVIEW

**Comment by AlexanderCicchino** [comment]
Currently running ctest on Narval. Will post log file once it is done.

**Comment by AlexanderCicchino** [comment]
[output_ctest_Jan_25_2024.log](https://github.com/dougshidong/PHiLiP/files/14067492/output_ctest_Jan_25_2024.log)

**Comment by AlexanderCicchino** [comment]
Fixed [Issue](https://github.com/dougshidong/PHiLiP/issues/223).

**Review by cpethrick — COMMENTED** [review]
Thanks for making this change! I have confirmed that everything builds. As there are no changes to the code's current functionality, should we leave a note somewhere indicating that these templating changes are untested?

My one comment on this PR is that the alignment of some functions has been impacted (e.g., line 674 of dg_base.hpp). If it doesn't take too long, could you restore the alignment on the dg classes?

Otherwise, thank you for going through the effort to template the operators classes!

**Comment by AlexanderCicchino** [comment]
Yes of course! Thanks for the catch! Fixed the alignment.

**Review by cpethrick — APPROVED** [review]

**Review by PranshulThakur — COMMENTED** [review]
Thanks a lot @AlexanderCicchino for templating Operators! It will help significantly to compute sensitivities with strong DG in future research projects (and probably weak DG too if we update it to use sum factorization). The PR looks great! 

To use strong DG with AD, do we need to make any additional modifications to strong DG? Also, is it possible to test AD on strong DG for inviscid cases by making slight modifications to the dRdW and dRdX unit tests in tests/unit_tests/sensitivities/?

**Comment by AlexanderCicchino** [comment]
Thanks @PranshulThakur! To use strong DG with AD: for inviscid problems it will need the modifications from weak DG's assemble_volume_term_derivatives for the dRdW and dRdX. I don't think there needs to be any changed in assemble volume/face/boundary functions. For viscous problems, strong DG's DR/Du will need to incorporate the auxiliary variable q and its respective solution:  DR/Du +DR/Dq*Dq/Du. Again, this can be computed outside of the assemble volume/face/boundary functions for the primary and auxiliary equations.

**Comment by PranshulThakur** [comment]
> Thanks @PranshulThakur! To use strong DG with AD: for inviscid problems it will need the modifications from weak DG's assemble_volume_term_derivatives for the dRdW and dRdX. I don't think there needs to be any changed in assemble volume/face/boundary functions. For viscous problems, strong DG's DR/Du will need to incorporate the auxiliary variable q and its respective solution: DR/Du +DR/Dq*Dq/Du. Again, this can be computed outside of the assemble volume/face/boundary functions for the primary and auxiliary equations.

Makes sense. Thanks for the explanation.

**Review by PranshulThakur — APPROVED** [review]
LGTM!

**Pull request merged**
