### PR TITLE
Script to compile on Beluga.

### PR DESCRIPTION
**Pull request by AlexanderCicchino**
Please modify the script to your local path accordingly.

### CODE REVIEW

**Comment by dougshidong** [comment]
It's a pull request about the compile script on Beluga, but it's modifying 61 files and 4k lines, thus "hiding" some merging that occurs. Please only commit the relevant changes to "Script to compile on Beluga" and make another PR that breaks down the other merge you want to achieve.

**Comment by dougshidong** [comment]
I now see why there are 4k lines. It's the PR from Julien. Can you look into "rebasing" your commits instead of creating a commit with 4k lines through a merge? The rebase would reorder Julien's commit before yours thus not necessitating a merge.

**Comment by AlexanderCicchino** [comment]
I don't see where the 4K is from. On my side it just says 84 lines added and 2 files changed.
I just rebased my master with upstream/master. Please let me know if that worked!

**Comment by dougshidong** [comment]
I don't see the rebase on this pull request. The 4k lines comes from the 2nd commit of this PR. What happened was that you merged the master branch into yours when you already had a commit. This creates a merging commit even though no merge happens. Instead, you would want to rebase locally such that the master branch is up-to-date with the latest changes and then apply your commits on that.

Since you've already done the push and the PR, rebasing will "change history" when your force puah on your side of things, which is fine because it won't affect anyone else until the PR is approved.

So please rebase your commits such that commit 4d15659382fb7272a30f2a13f6dfabd22f8e9875 disappears, and force push it. The PR should automatically update.

**Comment by AlexanderCicchino** [comment]
I think I might've messed up.

**Comment by dougshidong** [comment]
Hahaha I now see 38 commits.

**Comment by jbrillon** [comment]
This PR can be deleted, I've submitted a clean one (PR#77).

**Comment by dougshidong** [comment]
Closing as it was remedied in PR #77.

**Pull request closed without merging**
