### PR TITLE
ESFR and Split-Forms

### PR DESCRIPTION
**Pull request by AlexanderCicchino**
The strong form is updated with respect to ESFR and split-forms. The unsteady test cases have been corrected to give failing options. The metric terms have been corrected with a series of unit tests.

### CODE REVIEW

**Comment by AlexanderCicchino** [comment]
Also the log with ctest results to come in following days.

**Comment by dougshidong** [comment]
Please remove any .msh from the git history. Otherwise it pollutes the commit history with 80k lines.

**Comment by AlexanderCicchino** [comment]
My apologies! They've been removed.

**Comment by dougshidong** [comment]
Do it with a rebase and force push! You can probably ask @PranshulThakur or @jbrillon on how to remove it from git history. Otherwise, there is 400k lines of code now in your code (even if they're being removed they still show as part of git history)

**Comment by AlexanderCicchino** [comment]
Ok got it, will do!
There are also some tests failing to my surprise so it isn't yet ready for the merge :(

**Comment by dougshidong** [comment]
One more thing since you will have to rebase and force-push anyways: please try and keep those messages more decriptive and with less "lol"s. Those commits will be appearing in the merge!
image

**Comment by AlexanderCicchino** [comment]
Ok yes, fair enough! I will rebase before all of my commits and have just one commit associated with the merge.
Sorry about that :/

**Comment by dougshidong** [comment]
Any updates on this PR?

**Comment by AlexanderCicchino** [comment]
It is currently still failing tests, so unfortunately no worthy updates yet. :'(

**Comment by jbrillon** [comment]
Have you rebased your code yet? If you haven't, I'd start with that to resolve the conflicts first

**Comment by jbrillon** [comment]
and remove whatever files are causing such large changes (~400k currently)

**Comment by dougshidong** [comment]
There has to be a mesh in there for it to be 89k changes. Avoid using `git add -A`, and add the relevant files only.

**Comment by AlexanderCicchino** [comment]
As an update, I fixed all the changes and cleaned the code. It now also passes all tests. I am currently figuring out rebasing all the messy commit messages so that it is not in your history. Then after that I will upload the log files showing the passing tests.
Thank you for your patience :)

**Pull request closed without merging**
